services:
  edureach_ai:
    build: .
    container_name: edureach_ai
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
